version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@storybook/addon-docs"
    versions:
    - 6.2.7
    - 6.2.8
