const CalendarBaseClasses = (theme) => ({
  /// / RENDER HEADER ////
  '.header': {
    width: theme('width.full'),
    paddingTop: theme('spacing.7'),
    paddingBottom: theme('spacing.7'),
    borderBottomWidth: theme('borderWidth.DEFAULT'),
    borderColor: theme('colors.gray.200'),
    display: 'flex',
    flexWrap: 'wrap',
    justifyContent: 'space-around',
  },
  ///
  '.left-arrow-container': {
    display: 'flex',
    justifyContent: 'flex-start',
    flexGrow: theme('flexGrow.DEFAULT'),
    maxWidth: theme('maxWidth.full'),
    verticalAlign: 'middle',
    marginLeft: theme('spacing.10'),
    fontSize: theme('fontSize.2xl'),
    lineHeight: theme('lineHeight.8'),
    fontWeight: theme('fontWeight.bold'),
    color: theme('colors.gray.500'),
  },
  '.arrow-div': {
    display: 'inline-block',
    verticalAlign: 'middle',
    whiteSpace: 'nowrap',
    WebkitFontSmoothing: 'antialiased',
    MozOsxFontSmoothing: 'grayscale',
    cursor: theme('cursor.pointer'),
  },
  '.month-container': {
    display: 'flex',
    maxWidth: theme('maxWidth.full'),
    justifyContent: 'center',
    textAlign: 'center',
  },
  '.month-class': {
    fontSize: theme('fontSize.xl'),
    lineHeight: theme('lineHeight.7'),
    fontWeight: theme('fontWeight.bold'),
    color: theme('colors.gray.500'),
    textTransform: 'uppercase',
  },
  '.right-arrow-container': {
    display: 'flex',
    justifyContent: 'flex-end',
    flexGrow: theme('flexGrow.DEFAULT'),
    maxWidth: theme('maxWidth.full'),
    textAlign: 'right',
    marginRight: theme('spacing.10'),
    marginLeft: theme('spacing.10'),
    fontSize: theme('fontSize.2xl'),
    fontWeight: theme('fontWeight.bold'),
    color: theme('colors.gray.500'),
  },
  /// / RENDER DAYS ////
  '.days-container': {
    textTransform: 'uppercase',
    color: theme('colors.gray.400'),
    fontWeight: theme('fontWeight.medium'),
    paddingTop: theme('spacing.3'),
    paddingBottom: theme('spacing.3'),
    borderBottomWidth: theme('borderWidth.DEFAULT'),
    borderColor: theme('color.gray.200'),
    display: 'flex',
    flexWrap: 'wrap',
    justifyContent: 'space-around',
    width: theme('width.full'),
  },
  '.days-class': {
    display: 'flex',
    maxWidth: theme('maxWidth.full'),
    justifyContent: 'center',
    textAlign: 'center',
  },
  '.tile-class': {
    display: 'flex',
    flexGrow: theme('flexGrow.DEFAULT'),
    position: 'relative',
    overflow: 'hidden',
    backgroundColor: theme('colors.white'),
    transitionProperty: theme('transitionProperty.DEFAULT'),
    transitionTimingFunction: theme('transitionTimingFunction.DEFAULT'),
    transitionDuration: theme('transitionDuration.300'),
    maxWidth: theme('maxWidth.full'),
    /// hover:bg-gray-100
  },
  '.tile-characters-class': {
    display: 'flex',
    justifyContent: 'center',
    fontSize: theme('fontSize.lg'),
    lineHeight: theme('lineHeight.7'),
    alignItems: 'center',
    inset: theme('inset.0'),
    fontWeight: theme('fontWeight.bold'),
    position: 'absolute',
  },
  '.row-item': {
    display: 'flex',
    flexWrap: 'wrap',
    width: theme('width.full'),
  },
  '.rows': {
    fontWeight: theme('fontWeight.light'),
    color: theme('colors.gray.600'),
    backgroundColor: theme('colors.white'),
    position: 'relative',
  },
  '.calendar': {
    display: 'block',
    userSelect: 'none',
    position: 'relative',
    width: theme('width.full'),
    backgroundColor: theme('colors.white'),
    borderWidth: theme('borderWidth.DEFAULT'),
    borderColor: theme('color.gray.200'),
  },
});

module.exports = CalendarBaseClasses;

// const DropdownButtonBaseClasses = (theme) => ({
//   ".menu-button": {
//     "--tw-bg-opacity": "0.5",
//     backgroundColor: theme("colors.blue.600"),
//     transitionProperty: theme("transitionProperty.DEFAULT"),
//     transitionTimingFunction: theme("transitionTimingFunction.DEFAULT"),
//     transitionDelay: theme("transitionDelay.150"),
//     color: theme("colors.white"),
//     paddingTop: theme("spacing.2"),
//     paddingBottom: theme("spacing.2"),
//     paddingLeft: theme("spacing.4"),
//     paddingRight: theme("spacing.4"),
//     boxShadow: theme("boxShadow.md"),
//   },
//   ".menu-items-container": {
//     display: "flex",
//     flexDirection: "column",
//     // outline: theme("outline.none"),
//     // outlineOffset: theme("outline.none"),
//     paddingTop: theme("spacing.4"),
//     paddingBottom: theme("spacing.4"),
//     paddingLeft: theme("spacing.2"),
//     paddingRight: theme("spacing.2"),
//     borderWidth: theme("borderWidth.2"),
//     borderColor: theme("color.gray.400"),
//     boxShadow: theme("boxShadow.md"),
//     maxWidth: theme("spacing.80"),
//   },
// });

// module.exports = DropdownButtonBaseClasses;
