name: Test + Publish

on:
  push:
    paths:
      - '.changeset/**'
      - 'tw-plugins/**'
      - 'packages/**'
    branches:
      - main
      - next

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    strategy:
      # Use false if you integrate Cypress Dashboard
      # fail-fast: true
      # matrix:
      #   cypress:
      #     - working_directory: packages/accordion
      #     - working_directory: packages/multi-select

    steps:
      - id: yarn-cache
        name: Get Yarn cache path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js 12.x
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'

      - name: Configure max number of watchers
        run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

      - uses: actions/cache@v2
        name: Load Yarn cache
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies
        run: yarn install --frozen-lockfile && yarn bootstrap

      - name: Run Tests
        uses: cypress-io/github-action@v2
        with:
          start: yarn storybook:ci
          wait-on: 'http://localhost:6006'
          working-directory: ${{ matrix.cypress.working_directory }}

      - name: Setup CI Git User
        run: |
          git config --global user.email "matyas.furtos@gmail.com"
          git config --global user.name "Mátyás Fürtös"

      - name: Build Packages
        run: yarn build

      - name: Publish Packages
        uses: changesets/action@master
        with:
          publish: yarn release
          commit: 'chore(release): version packages'
        env:
          NPM_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
          GITHUB_TOKEN: ${{secrets.GH_AUTH_TOKEN}}
